kind: Site
metadata:
  name: west
  namespace: hello-world-west
spec:
  defaultIssuer: &lt;your-ca&gt;
  linkAccess: default
--
kind: AccessGrant
metadata:
  name: west-grant
  namespace: west
spec:
  code: &lt;your-secret-code&gt;
--
kind: Listener
metadata:
  name: backend
  namespace: hello-world-west
spec:
  routingKey: backend
  host: backend
  port: 8080
