kind: Site
metadata:
  name: west
  namespace: hello-world-west
spec:
  defaultIssuer: your-ca
  linkAccess: default
--
kind: AccessGrant
metadata:
  name: west-grant
  namespace: west
spec:
  code: your-secret-code

--
kind: Listener
metadata:
  name: backend
  namespace: hello-world-west
spec:
  routingKey: backend
  host: backend
  port: 8080
