[#skupper-website]
= Skupper website
:source-filename: /home/paulwright/repos/a/skupper-website/README.md

image::https://github.com/skupperproject/skupper-website/actions/workflows/main.yaml/badge.svg[main,link=https://github.com/skupperproject/skupper-website/actions/workflows/main.yaml]

[#project-commands]
== Project commands

You can use the `./plano` command in the root of the project to perform project tasks.
It accepts a subcommand.
Use `./plano --help` to list the available commands.

[#rendering-the-site]
== Rendering the site

You can use the `./plano render` command in the root of the project to render the site:

[source,console]
----
$ ./plano render
--> render
Rendering input files
<-- render
OK (0.21s)
----

For development, you can serve the site locally.
Any changes you make to the input files are rendered on demand.

[source,console]
----
$ ./plano serve
--> serve
Rendering input files
Watching for input file changes
Serving at http://localhost:8080
Starting LiveReload v0.9.1 for /home/jross/code/skupper-website-ssorj/output on port 35729.
----

[#generating-the-docs]
== Generating the docs

The docs source is in a distinct repo, skupper-docs and are written in AsciiDoc.

The process of publishing these docs to the Skupper website uses https://docs.antora.org[Antora] to convert them to HTML.

. Install  https://docs.antora.org[Antora].
. Run `./plano generate-docs` to create HTML from the `master` branch of `skupper-docs`.
. Run `./plano render` to populate the `docs` directory of this repo with the HTML files from step 1.
