# See https://github.com/actions/starter-workflows/blob/main/pages/static.yml
on:
  push:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: pages
  cancel-in-progress: false
jobs:
  main:
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    runs-on: ubuntu-latest
    steps:
      - name: Set up environment
        run: |
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"
          echo "PLANO_COLOR=1" >> "$GITHUB_ENV"
          pip install pyyaml
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v5
      # - run: ./plano test
      - run: ./plano render
      - uses: actions/upload-pages-artifact@v3
        with:
          path: output
      - uses: actions/deploy-pages@v4
        id: deployment
